name: WordPress Coding Standards checker
on: pull_request

jobs:
  phpcs:
      name: WPCS checker
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: WPCS check
          uses: 10up/wpcs-action@stable
          with:
            enable_warnings: true
            standard: 'WordPress-VIP-Go'
            use_local_config: true
