name: WordPress Coding Standards checker
on: pull_request

jobs:
  phpcs:
      name: WPCS checker
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: WPCS check
          uses: 10up/wpcs-action@stable
          with:
            enable_warnings: true
            repo_branch: 'master'
            use_local_config: 'true' # Use local phpcs.xml config
